replicaCount: 2
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
  hosts:
    - wp.swarm.pw
  tls:
    - secretName: wp.swarm.pw-tls
      hosts:
        - wp.swarm.pw
