version: "3.3"

services:
  app:
    image: ilyasotkov/rails-react-boilerplate:latest
    build: .
    command: |
      /bin/bash -c \
      "rm -f tmp/pids/server.pid \
      && bundle exec rails server -p 3001 -b '0.0.0.0' \
      & bundle exec guard -i  \
      & ./bin/webpack-dev-server"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - WEBPACKER_DEV_SERVER_HOT=true
    ports:
      - "3003:3001"
      - "3035:3035"
      - "35729:35729"
    depends_on:
      - db
  db:
    image: postgres:10.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
