default: &default
  adapter: postgresql
  encoding: utf8
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test

production:
  host: <%= ENV["POSTGRES_HOST"] %>
  <<: *default
  database: db_production
